#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// Code is generated by Telerik Add OpenAccess Service Wizard
// using PlainIDataService.tt template

namespace HCAEntityService
{
	using System.ServiceModel;
	using HCAEntityService.Dto;
	using System;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Collections;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
    using System.ServiceModel.Web;
    using HCAEntityService.Utils;

	/// <summary>
	/// HCAEntityModelService interface.
	/// </summary>
	[ServiceContract]
	public interface IHCAEntityModelService
	{
        /// <summary>
        /// Returns all candidates.
        /// </summary>
        /// <returns></returns>
        [OperationContract]
        [WebInvoke(Method = "GET",
         BodyStyle = WebMessageBodyStyle.Bare, UriTemplate = "/Candidates", ResponseFormat = WebMessageFormat.Json)]
        AppGenericServiceResponse<CandidateDataList> ReadCandidates();

        [OperationContract]
        [WebInvoke(Method = "GET",
         BodyStyle = WebMessageBodyStyle.Bare, UriTemplate = "/Candidates/{dtoKey}", ResponseFormat = WebMessageFormat.Json)]
        AppGenericServiceResponse<CandidateDto> ReadCandidate(string dtoKey);


        [OperationContract]
        [WebInvoke(Method = "POST",RequestFormat = WebMessageFormat.Json,
        BodyStyle = WebMessageBodyStyle.Bare, UriTemplate = "/Candidates", ResponseFormat = WebMessageFormat.Json)]
        AppGenericServiceResponse<string> CreateCandidate(CandidateDto candidate);

	}
}
#pragma warning restore 1591
