#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using HRBlock.Library.BusinessObject.HCA;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace HCAEntityService.Dto
{
	public interface IDtoWithKey
	{
		string DtoKey { get; set; }
	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CandidateDto))]
	public partial class LicenseDto : IDtoWithKey
	{
		public LicenseDto()
		{
		}
		
		public LicenseDto(int _id, int _candidateId, string _licenseNo, string _state, string _licenseType, DateTime _dateAcquired, DateTime? _dateExpires, DateTime? _dateRenewed, int _createdById, DateTime _dateCreated, int? _modifiedById, DateTime? _dateModified, bool _active, CandidateDto _candidate)
		{
			this.Id = _id;
			this.CandidateId = _candidateId;
			this.LicenseNo = _licenseNo;
			this.State = _state;
			this.LicenseType = _licenseType;
			this.DateAcquired = _dateAcquired;
			this.DateExpires = _dateExpires;
			this.DateRenewed = _dateRenewed;
			this.CreatedById = _createdById;
			this.DateCreated = _dateCreated;
			this.ModifiedById = _modifiedById;
			this.DateModified = _dateModified;
			this.Active = _active;
			this.Candidate = _candidate;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int CandidateId { get;set; }

		[DataMember]
		public virtual string LicenseNo { get;set; }

		[DataMember]
		public virtual string State { get;set; }

		[DataMember]
		public virtual string LicenseType { get;set; }

		[DataMember]
		public virtual DateTime DateAcquired { get;set; }

		[DataMember]
		public virtual DateTime? DateExpires { get;set; }

		[DataMember]
		public virtual DateTime? DateRenewed { get;set; }

		[DataMember]
		public virtual int CreatedById { get;set; }

		[DataMember]
		public virtual DateTime DateCreated { get;set; }

		[DataMember]
		public virtual int? ModifiedById { get;set; }

		[DataMember]
		public virtual DateTime? DateModified { get;set; }

		[DataMember]
		public virtual bool Active { get;set; }

		[DataMember]
		public virtual CandidateDto Candidate { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CandidateDto))]
	public partial class CarrierAssignmentDto : IDtoWithKey
	{
		public CarrierAssignmentDto()
		{
		}
		
		public CarrierAssignmentDto(int _id, int _candidateId, string _code, string _agentId, string _productType, string _state, DateTime? _dateAcquired, DateTime? _dateExpired, DateTime? _dateRenewed, int _createdById, DateTime _dateCreated, int? _modifiedById, DateTime? _dateModified, bool _active, CandidateDto _candidate)
		{
			this.Id = _id;
			this.CandidateId = _candidateId;
			this.Code = _code;
			this.AgentId = _agentId;
			this.ProductType = _productType;
			this.State = _state;
			this.DateAcquired = _dateAcquired;
			this.DateExpired = _dateExpired;
			this.DateRenewed = _dateRenewed;
			this.CreatedById = _createdById;
			this.DateCreated = _dateCreated;
			this.ModifiedById = _modifiedById;
			this.DateModified = _dateModified;
			this.Active = _active;
			this.Candidate = _candidate;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int CandidateId { get;set; }

		[DataMember]
		public virtual string Code { get;set; }

		[DataMember]
		public virtual string AgentId { get;set; }

		[DataMember]
		public virtual string ProductType { get;set; }

		[DataMember]
		public virtual string State { get;set; }

		[DataMember]
		public virtual DateTime? DateAcquired { get;set; }

		[DataMember]
		public virtual DateTime? DateExpired { get;set; }

		[DataMember]
		public virtual DateTime? DateRenewed { get;set; }

		[DataMember]
		public virtual int CreatedById { get;set; }

		[DataMember]
		public virtual DateTime DateCreated { get;set; }

		[DataMember]
		public virtual int? ModifiedById { get;set; }

		[DataMember]
		public virtual DateTime? DateModified { get;set; }

		[DataMember]
		public virtual bool Active { get;set; }

		[DataMember]
		public virtual CandidateDto Candidate { get;set; }

	}

    [DataContract]
    public class CandidateDataList
    {
        [DataMember]
        public List<CandidateDto> CandidateList;
    }


	[DataContract(IsReference = false)]
	[KnownType(typeof(LicenseDto))]
	[KnownType(typeof(CarrierAssignmentDto))]
	[KnownType(typeof(CertificationDto))]
	public partial class CandidateDto : IDtoWithKey
	{
		public CandidateDto()
		{
		}
		
		public CandidateDto(int _id, int _moduleId, string _firstName, string _lastName, string _email, string _employeeId, string _employeeRole, int? _officeId, string _deptId, string _districtId, string _region, string _market, string _officePhoneNo, string _fFMUserId, int _createdById, DateTime _dateCreated, int? _modifiedById, DateTime? _dateModified, bool _active, IList<LicenseDto> _licenses, IList<CarrierAssignmentDto> _carrierAssignments, IList<CertificationDto> _certifications)
		{
			this.Id = _id;
			this.ModuleId = _moduleId;
			this.FirstName = _firstName;
			this.LastName = _lastName;
			this.Email = _email;
			this.EmployeeId = _employeeId;
			this.EmployeeRole = _employeeRole;
			this.OfficeId = _officeId;
			this.DeptId = _deptId;
			this.DistrictId = _districtId;
			this.Region = _region;
			this.Market = _market;
			this.OfficePhoneNo = _officePhoneNo;
			this.FFMUserId = _fFMUserId;
			this.CreatedById = _createdById;
			this.DateCreated = _dateCreated;
			this.ModifiedById = _modifiedById;
			this.DateModified = _dateModified;
			this.Active = _active;
			this.Licenses = _licenses;
			this.CarrierAssignments = _carrierAssignments;
			this.Certifications = _certifications;
		}



       


		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int ModuleId { get;set; }

		[DataMember]
		public virtual string FirstName { get;set; }

		[DataMember]
		public virtual string LastName { get;set; }

		[DataMember]
		public virtual string Email { get;set; }

		[DataMember]
		public virtual string EmployeeId { get;set; }

		[DataMember]
		public virtual string EmployeeRole { get;set; }

		[DataMember]
		public virtual int? OfficeId { get;set; }

		[DataMember]
		public virtual string DeptId { get;set; }

		[DataMember]
		public virtual string DistrictId { get;set; }

		[DataMember]
		public virtual string Region { get;set; }

		[DataMember]
		public virtual string Market { get;set; }

		[DataMember]
		public virtual string OfficePhoneNo { get;set; }

		[DataMember]
		public virtual string FFMUserId { get;set; }

		[DataMember]
		public virtual int CreatedById { get;set; }

		[DataMember]
		public virtual DateTime DateCreated { get;set; }

		[DataMember]
		public virtual int? ModifiedById { get;set; }

		[DataMember]
		public virtual DateTime? DateModified { get;set; }

		[DataMember]
		public virtual bool Active { get;set; }

		[DataMember]
		public virtual IList<LicenseDto> Licenses { get;set; }

		[DataMember]
		public virtual IList<CarrierAssignmentDto> CarrierAssignments { get;set; }

		[DataMember]
		public virtual IList<CertificationDto> Certifications { get;set; }

	}
	
	[DataContract(IsReference = true)]
	[KnownType(typeof(CandidateDto))]
	public partial class CertificationDto : IDtoWithKey
	{
		public CertificationDto()
		{
		}
		
		public CertificationDto(int _id, int _candidateId, string _nPNId, DateTime? _dateAcquired, DateTime? _dateExpired, DateTime? _dateRenewed, int _createdById, DateTime _createdDate, int? _modifiedById, DateTime? _dateModified, bool _active, CandidateDto _candidate)
		{
			this.Id = _id;
			this.CandidateId = _candidateId;
			this.NPNId = _nPNId;
			this.DateAcquired = _dateAcquired;
			this.DateExpired = _dateExpired;
			this.DateRenewed = _dateRenewed;
			this.CreatedById = _createdById;
			this.CreatedDate = _createdDate;
			this.ModifiedById = _modifiedById;
			this.DateModified = _dateModified;
			this.Active = _active;
			this.Candidate = _candidate;
		}
		
		[DataMember]
		public virtual string DtoKey { get; set; }
		
		[DataMember]
		public virtual int Id { get;set; }

		[DataMember]
		public virtual int CandidateId { get;set; }

		[DataMember]
		public virtual string NPNId { get;set; }

		[DataMember]
		public virtual DateTime? DateAcquired { get;set; }

		[DataMember]
		public virtual DateTime? DateExpired { get;set; }

		[DataMember]
		public virtual DateTime? DateRenewed { get;set; }

		[DataMember]
		public virtual int CreatedById { get;set; }

		[DataMember]
		public virtual DateTime CreatedDate { get;set; }

		[DataMember]
		public virtual int? ModifiedById { get;set; }

		[DataMember]
		public virtual DateTime? DateModified { get;set; }

		[DataMember]
		public virtual bool Active { get;set; }

		[DataMember]
		public virtual CandidateDto Candidate { get;set; }

	}
	
}
#pragma warning restore 1591
