#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using HRBlock.Library.BusinessObject.HCA;

namespace HRBlock.Library.BusinessObject.HCA	
{
	public partial class HCAEntityModel : OpenAccessContext, IHCAEntityModelUnitOfWork
	{
		private static string connectionStringName = @"HCA";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("HCAEntityModel.rlinq");
		
		public HCAEntityModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public HCAEntityModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public HCAEntityModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public HCAEntityModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public HCAEntityModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<License> Licenses 
		{
			get
			{
				return this.GetAll<License>();
			}
		}
		
		public IQueryable<CarrierAssignment> CarrierAssignments 
		{
			get
			{
				return this.GetAll<CarrierAssignment>();
			}
		}
		
		public IQueryable<Candidate> Candidates 
		{
			get
			{
				return this.GetAll<Candidate>();
			}
		}
		
		public IQueryable<Certification> Certifications 
		{
			get
			{
				return this.GetAll<Certification>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			return backend;
		}
	}
	
	public interface IHCAEntityModelUnitOfWork : IUnitOfWork
	{
		IQueryable<License> Licenses
		{
			get;
		}
		IQueryable<CarrierAssignment> CarrierAssignments
		{
			get;
		}
		IQueryable<Candidate> Candidates
		{
			get;
		}
		IQueryable<Certification> Certifications
		{
			get;
		}
	}
}
#pragma warning restore 1591
