#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using HRBlock.Library.BusinessObject.HCA;

namespace HRBlock.Library.BusinessObject.HCA	
{
	public partial class LocationEntityModel : OpenAccessContext, ILocationEntityModelUnitOfWork
	{
		private static string connectionStringName = @"ELMS";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("LocationEntitiesModel.rlinq");
		
		public LocationEntityModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public LocationEntityModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public LocationEntityModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public LocationEntityModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public LocationEntityModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Location> Locations 
		{
			get
			{
				return this.GetAll<Location>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
			backend.Logging.MetricStoreSnapshotInterval = 0;
			backend.Runtime.ClassBehavior = DataAccessKind.ReadOnly;
			return backend;
		}
	}
	
	public interface ILocationEntityModelUnitOfWork : IUnitOfWork
	{
		IQueryable<Location> Locations
		{
			get;
		}
	}
}
#pragma warning restore 1591
