#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using HRBlock.Library.BusinessObject.HCA;

namespace HRBlock.Library.BusinessObject.HCA	
{
	public partial class Candidate
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private int _moduleId;
		public virtual int ModuleId
		{
			get
			{
				return this._moduleId;
			}
			set
			{
				this._moduleId = value;
			}
		}
		
		private string _firstName;
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				this._firstName = value;
			}
		}
		
		private string _lastName;
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				this._lastName = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _employeeId;
		public virtual string EmployeeId
		{
			get
			{
				return this._employeeId;
			}
			set
			{
				this._employeeId = value;
			}
		}
		
		private string _employeeRole;
		public virtual string EmployeeRole
		{
			get
			{
				return this._employeeRole;
			}
			set
			{
				this._employeeRole = value;
			}
		}
		
		private int? _officeId;
		public virtual int? OfficeId
		{
			get
			{
				return this._officeId;
			}
			set
			{
				this._officeId = value;
			}
		}
		
		private string _deptId;
		public virtual string DeptId
		{
			get
			{
				return this._deptId;
			}
			set
			{
				this._deptId = value;
			}
		}
		
		private string _districtId;
		public virtual string DistrictId
		{
			get
			{
				return this._districtId;
			}
			set
			{
				this._districtId = value;
			}
		}
		
		private string _region;
		public virtual string Region
		{
			get
			{
				return this._region;
			}
			set
			{
				this._region = value;
			}
		}
		
		private string _market;
		public virtual string Market
		{
			get
			{
				return this._market;
			}
			set
			{
				this._market = value;
			}
		}
		
		private string _officePhoneNo;
		public virtual string OfficePhoneNo
		{
			get
			{
				return this._officePhoneNo;
			}
			set
			{
				this._officePhoneNo = value;
			}
		}
		
		private string _fFMUserId;
		public virtual string FFMUserId
		{
			get
			{
				return this._fFMUserId;
			}
			set
			{
				this._fFMUserId = value;
			}
		}
		
		private int _createdById;
		public virtual int CreatedById
		{
			get
			{
				return this._createdById;
			}
			set
			{
				this._createdById = value;
			}
		}
		
		private DateTime _dateCreated;
		public virtual DateTime DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				this._dateCreated = value;
			}
		}
		
		private int? _modifiedById;
		public virtual int? ModifiedById
		{
			get
			{
				return this._modifiedById;
			}
			set
			{
				this._modifiedById = value;
			}
		}
		
		private DateTime? _dateModified;
		public virtual DateTime? DateModified
		{
			get
			{
				return this._dateModified;
			}
			set
			{
				this._dateModified = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private IList<License> _licenses = new List<License>();
		public virtual IList<License> Licenses
		{
			get
			{
				return this._licenses;
			}
		}
		
		private IList<CarrierAssignment> _carrierAssignments = new List<CarrierAssignment>();
		public virtual IList<CarrierAssignment> CarrierAssignments
		{
			get
			{
				return this._carrierAssignments;
			}
		}
		
		private IList<Certification> _certifications = new List<Certification>();
		public virtual IList<Certification> Certifications
		{
			get
			{
				return this._certifications;
			}
		}
		
	}
}
#pragma warning restore 1591
