#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace HRBlock.Library.BusinessObject.HCA	
{
	public partial class Location
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _divNameNo;
		public virtual string DivNameNo
		{
			get
			{
				return this._divNameNo;
			}
			set
			{
				this._divNameNo = value;
			}
		}
		
		private string _regionNameNo;
		public virtual string RegionNameNo
		{
			get
			{
				return this._regionNameNo;
			}
			set
			{
				this._regionNameNo = value;
			}
		}
		
		private int? _topDistrictGlDepId;
		public virtual int? TopDistrictGlDepId
		{
			get
			{
				return this._topDistrictGlDepId;
			}
			set
			{
				this._topDistrictGlDepId = value;
			}
		}
		
		private System.Nullable<System.Char> _mainOfficeCd;
		public virtual System.Nullable<System.Char> MainOfficeCd
		{
			get
			{
				return this._mainOfficeCd;
			}
			set
			{
				this._mainOfficeCd = value;
			}
		}
		
		private int? _officeGlDepId;
		public virtual int? OfficeGlDepId
		{
			get
			{
				return this._officeGlDepId;
			}
			set
			{
				this._officeGlDepId = value;
			}
		}
		
		private System.Nullable<System.Char> _activeIndYN;
		public virtual System.Nullable<System.Char> ActiveIndYN
		{
			get
			{
				return this._activeIndYN;
			}
			set
			{
				this._activeIndYN = value;
			}
		}
		
		private System.Nullable<System.Char> _taxPrepYN;
		public virtual System.Nullable<System.Char> TaxPrepYN
		{
			get
			{
				return this._taxPrepYN;
			}
			set
			{
				this._taxPrepYN = value;
			}
		}
		
		private System.Nullable<System.Char> _seasonalCloseYN;
		public virtual System.Nullable<System.Char> SeasonalCloseYN
		{
			get
			{
				return this._seasonalCloseYN;
			}
			set
			{
				this._seasonalCloseYN = value;
			}
		}
		
		private int? _seasonalDataReportedYN;
		public virtual int? SeasonalDataReportedYN
		{
			get
			{
				return this._seasonalDataReportedYN;
			}
			set
			{
				this._seasonalDataReportedYN = value;
			}
		}
		
		private string _addressLine1Txt;
		public virtual string AddressLine1Txt
		{
			get
			{
				return this._addressLine1Txt;
			}
			set
			{
				this._addressLine1Txt = value;
			}
		}
		
		private string _addressLine2Txt;
		public virtual string AddressLine2Txt
		{
			get
			{
				return this._addressLine2Txt;
			}
			set
			{
				this._addressLine2Txt = value;
			}
		}
		
		private string _cityNm;
		public virtual string CityNm
		{
			get
			{
				return this._cityNm;
			}
			set
			{
				this._cityNm = value;
			}
		}
		
		private string _stateOrProvinceCd;
		public virtual string StateOrProvinceCd
		{
			get
			{
				return this._stateOrProvinceCd;
			}
			set
			{
				this._stateOrProvinceCd = value;
			}
		}
		
		private string _postalCd;
		public virtual string PostalCd
		{
			get
			{
				return this._postalCd;
			}
			set
			{
				this._postalCd = value;
			}
		}
		
		private string _countyNm;
		public virtual string CountyNm
		{
			get
			{
				return this._countyNm;
			}
			set
			{
				this._countyNm = value;
			}
		}
		
		private int? _affiliateNo;
		public virtual int? AffiliateNo
		{
			get
			{
				return this._affiliateNo;
			}
			set
			{
				this._affiliateNo = value;
			}
		}
		
		private string _busPhone;
		public virtual string BusPhone
		{
			get
			{
				return this._busPhone;
			}
			set
			{
				this._busPhone = value;
			}
		}
		
		private string _fax;
		public virtual string Fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				this._fax = value;
			}
		}
		
		private string _seasonalCloseDt;
		public virtual string SeasonalCloseDt
		{
			get
			{
				return this._seasonalCloseDt;
			}
			set
			{
				this._seasonalCloseDt = value;
			}
		}
		
		private string _seasonalOpenDt;
		public virtual string SeasonalOpenDt
		{
			get
			{
				return this._seasonalOpenDt;
			}
			set
			{
				this._seasonalOpenDt = value;
			}
		}
		
		private System.Nullable<System.Char> _openYearRoundYN;
		public virtual System.Nullable<System.Char> OpenYearRoundYN
		{
			get
			{
				return this._openYearRoundYN;
			}
			set
			{
				this._openYearRoundYN = value;
			}
		}
		
		private int? _districtGlDepId;
		public virtual int? DistrictGlDepId
		{
			get
			{
				return this._districtGlDepId;
			}
			set
			{
				this._districtGlDepId = value;
			}
		}
		
		private string _districtName;
		public virtual string DistrictName
		{
			get
			{
				return this._districtName;
			}
			set
			{
				this._districtName = value;
			}
		}
		
		private string _orgzMgrNm;
		public virtual string OrgzMgrNm
		{
			get
			{
				return this._orgzMgrNm;
			}
			set
			{
				this._orgzMgrNm = value;
			}
		}
		
		private string _divisionMgrNm;
		public virtual string DivisionMgrNm
		{
			get
			{
				return this._divisionMgrNm;
			}
			set
			{
				this._divisionMgrNm = value;
			}
		}
		
		private short? _orgzOwnershipId;
		public virtual short? OrgzOwnershipId
		{
			get
			{
				return this._orgzOwnershipId;
			}
			set
			{
				this._orgzOwnershipId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
